#!/bin/bash
ACTUAL_PATH=`dirname "$0"`
LINKED_PATH=`readlink "$0"`
ASSEMBLY_PATH=$([ "$LINKED_PATH" ] && echo `dirname "$LINKED_PATH"` || echo "$ACTUAL_PATH")
mono --arch=64 $ASSEMBLY_PATH/Nostrand.exe "$@"